import { GPTAnalyzer } from "@/app/utils/analyzer/GPTAnalyzer";
import { Perception } from "@/app/utils/perception/perception";
import { NextResponse } from "next/server";

// ? we can move these constants to a constant file
const gptWords = 3;
const prompt = `
Can you pull out one or two keywords representing the mood or emotion from the following text. And make sure to only respond with the keywords as comma seperated. I don't want any other text in your resonse except the comma seperated keywords.
`;
const gpt = new GPTAnalyzer(
  gptWords,
  prompt,
  process.env.OPEN_AI_API_KEY,
  "gpt-3.5-turbo",
);

const tokenEndpoint =
process.env.PERCEPTION_KEY;
const apiEndpoint =
  "https://staging-api.perception.io/v1/recommendations/palettes";
const perception = new Perception(tokenEndpoint, apiEndpoint);

export async function POST(req) {
  const { content, numsOfColors } = await req.json();
  // analyze through GPT
  const gptResponse = await gpt.analyze(content);
  const terms = gptResponse.split(",").map((term) => term.trim());
  // topTerm generated by perception is not used. We use GPT's reponse instead
  const { hexcodes } = await perception.generate(terms, numsOfColors);

  return NextResponse.json({
    colors: hexcodes,
    terms: terms,
  });
}
